#!/usr/bin/env bash
#
# cbm-wire-llm.sh — point the installed MCP clients at a wrapper that supplies
# the LLM credentials.
#
# THE PROBLEM THIS SOLVES. codebase-memory-mcp's LLM enrichment pass reads its
# configuration from the environment, but the MCP server is not started by your
# shell -- it is started by whichever agent hosts it (omp, Claude Code, Codex,
# OpenCode, ...). Nothing you export interactively reaches it. Worse, the server
# starts a long-lived daemon that serves every later index request with ITS OWN
# environment, so exporting the variables after a daemon is already running
# changes nothing at all.
#
# The result is silent: indexing still succeeds, but every file gets placeholder
# prose ("stub purpose: <path> is a <py> source file") instead of a description,
# and that placeholder text goes into the BM25 body of every file.
#
# HOW THIS FIXES IT. A wrapper script sources the credentials from one file and
# execs the real binary; each client's `command` is pointed at the wrapper. The
# secret therefore stays in ONE place instead of being copied into every client
# config, which is what `env` blocks in each config would require.
#
# IDEMPOTENT. Re-run it after any `install` (which rewrites the client configs
# back to the bare binary path) or after `update`. It backs up each config once,
# on first change, and never overwrites that backup -- so --revert always
# restores the state you had before this script ever ran.
#
# Usage:
#   cbm-wire-llm.sh [--dry-run] [--revert]
#                   [--env-file PATH] [--binary PATH] [--wrapper PATH]
#
#   --dry-run        Show what would change; touch nothing.
#   --revert         Restore every config from its backup.
#   --env-file PATH  Credentials file (default: ~/.cbm-llm.env)
#   --binary PATH    The installed binary (default: <wrapper dir>/codebase-memory-mcp)
#   --wrapper PATH   Where to put the wrapper (default: <binary dir>/codebase-memory-mcp-llm)
#
set -euo pipefail

ENV_FILE="${CBM_LLM_ENV_FILE:-$HOME/.cbm-llm.env}"
BINARY="${CBM_BINARY:-$HOME/.local/bin/codebase-memory-mcp}"
WRAPPER="${CBM_WRAPPER:-$HOME/.local/bin/codebase-memory-mcp-llm}"
DRY_RUN=false
REVERT=false

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=true ;;
        --revert) REVERT=true ;;
        --env-file) shift; ENV_FILE="${1:?--env-file needs a path}" ;;
        --binary) shift; BINARY="${1:?--binary needs a path}" ;;
        --wrapper) shift; WRAPPER="${1:?--wrapper needs a path}" ;;
        -h | --help) sed -n '2,37p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *)
            echo "cbm-wire-llm: unknown argument: $1" >&2
            exit 2
            ;;
    esac
    shift
done

# Config files that can carry an MCP server command. Only the ones that exist
# AND mention this binary are touched, so the list can be generous.
candidates() {
    cat <<EOF
$HOME/.omp/agent/mcp.json
$HOME/.claude.json
$HOME/.codex/config.toml
$HOME/.config/opencode/opencode.json
$HOME/.config/Code/User/mcp.json
$HOME/.config/Code - Insiders/User/mcp.json
$HOME/.config/VSCodium/User/mcp.json
$HOME/.copilot/mcp-config.json
$HOME/.gemini/settings.json
$HOME/.grok/config.toml
$HOME/.cursor/mcp.json
$HOME/.codeium/windsurf/mcp_config.json
$HOME/.continue/config.json
$HOME/.qwen/settings.json
$HOME/.config/zed/settings.json
$HOME/.kiro/settings/mcp.json
$HOME/.amp/settings.json
$HOME/.factory/mcp.json
EOF
}

# ── --revert ────────────────────────────────────────────────────────────────
if [ "$REVERT" = true ]; then
    restored=0
    while IFS= read -r f; do
        [ -f "$f.bak-cbm-llm" ] || continue
        if [ "$DRY_RUN" = true ]; then
            echo "would restore  $f"
        else
            cp -p "$f.bak-cbm-llm" "$f"
            echo "restored       $f"
        fi
        restored=$((restored + 1))
    done < <(candidates)
    echo
    echo "restored $restored config(s) from .bak-cbm-llm"
    echo "note: the wrapper ($WRAPPER) is left in place; remove it if you want it gone."
    exit 0
fi

# ── 1. the wrapper ──────────────────────────────────────────────────────────
if [ ! -x "$BINARY" ]; then
    echo "cbm-wire-llm: no executable at $BINARY" >&2
    echo "  Install first:  codebase-memory-mcp install -y" >&2
    echo "  Or point at it: cbm-wire-llm.sh --binary /path/to/codebase-memory-mcp" >&2
    exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
    echo "cbm-wire-llm: WARNING: $ENV_FILE does not exist." >&2
    echo "  The wrapper will still be installed, but with no CBM_LLM_URL the pass" >&2
    echo "  writes placeholder prose and the index says so (llm_enrich.kind=\"stub\")." >&2
    echo "  Create it with at least:" >&2
    echo "      export CBM_LLM_URL=https://api.deepseek.com/v1" >&2
    echo "      export CBM_LLM_API_KEY=..." >&2
fi

wrapper_body() {
    cat <<EOF
#!/usr/bin/env bash
# Generated by cbm-wire-llm.sh -- re-run that script rather than editing here.
#
# Supplies the LLM credentials to the MCP server, which the hosting agent
# starts without your shell environment, and which then hands that environment
# to the long-lived daemon that serves every index request.
#
# Credentials live in exactly one file ($ENV_FILE) so they are not copied into
# every client config.
set -a
[ -f "$ENV_FILE" ] && . "$ENV_FILE"
set +a
exec "$BINARY" "\$@"
EOF
}

if [ "$DRY_RUN" = true ]; then
    echo "would write    $WRAPPER"
else
    mkdir -p "$(dirname "$WRAPPER")"
    wrapper_body >"$WRAPPER"
    chmod 700 "$WRAPPER"
    echo "wrote          $WRAPPER"
fi

# ── 2. point the client configs at it ───────────────────────────────────────
# Only ever rewrites the bare binary path when it is quoted, which is how every
# MCP JSON/TOML config spells a command. That also makes a re-run a no-op:
# "codebase-memory-mcp-llm" does not contain the quoted "codebase-memory-mcp".
changed=0
skipped=0
while IFS= read -r f; do
    [ -f "$f" ] || continue
    if grep -q -- "$WRAPPER" "$f" 2>/dev/null; then
        skipped=$((skipped + 1))
        continue
    fi
    if ! grep -q -- "$BINARY" "$f" 2>/dev/null; then
        continue
    fi
    if [ "$DRY_RUN" = true ]; then
        echo "would rewire   $f"
        changed=$((changed + 1))
        continue
    fi
    # A backup is written ONCE, on first change, and never overwritten -- so
    # --revert restores the pre-wiring state however many times this runs.
    [ -f "$f.bak-cbm-llm" ] || cp -p "$f" "$f.bak-cbm-llm"
    tmp="$(mktemp)"
    sed -e "s|${BINARY}\"|${WRAPPER}\"|g" \
        -e "s|${BINARY}'|${WRAPPER}'|g" "$f" >"$tmp"
    if [ ! -s "$tmp" ]; then
        echo "  SKIPPED (empty result, left alone): $f" >&2
        rm -f "$tmp"
        continue
    fi
    mv "$tmp" "$f"
    # The trailing-boundary guard matters: the bare path is a PREFIX of the
    # wrapper path, so a plain substring probe reports a leftover reference in
    # every file it just rewired.
    if grep -qE -- "${BINARY}([^[:alnum:]_-]|$)" "$f" 2>/dev/null; then
        echo "  rewired        $f"
        echo "    note: still references the bare binary path (unusual quoting?) -- check it." >&2
    else
        echo "  rewired        $f"
    fi
    changed=$((changed + 1))
done < <(candidates)

echo
echo "rewired $changed config(s), $skipped already wired"

# ── 3. the restart nobody can do for you ────────────────────────────────────
echo
echo "NEXT: restart your agent session(s) -- omp, Claude Code, Codex, ..."
echo "  A daemon already running keeps the environment it was started with, so"
echo "  the change only takes effect when the MCP server is launched again."
echo "  Check which environment is live with:"
echo "      pid=\$(pgrep -f cbm-daemon-internal | head -1)"
echo "      tr '\\0' '\\n' < /proc/\$pid/environ | grep CBM_LLM"
echo "  CBM_LLM_URL should be there. If it is not, the daemon predates this run."
